In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
CarPrice=pd.read_csv('/content/CarPrice_Assignment.csv')

Start from understanding the data, what were your observations initially when you
started working on the data?

In [4]:
CarPrice.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [5]:
CarPrice.tail()

car_ID  symboling          CarName fueltype aspiration doornumber  \
200     201         -1  volvo 145e (sw)      gas        std       four   
201     202         -1      volvo 144ea      gas      turbo       four   
202     203         -1      volvo 244dl      gas        std       four   
203     204         -1        volvo 246   diesel      turbo       four   
204     205         -1      volvo 264gl      gas      turbo       four   

    carbody drivewheel enginelocation  wheelbase  ...  enginesize  fuelsystem  \
200   sedan        rwd          front      109.1  ...         141        mpfi   
201   sedan        rwd          front      109.1  ...         141        mpfi   
202   sedan        rwd          front      109.1  ...         173        mpfi   
203   sedan        rwd          front      109.1  ...         145         idi   
204   sedan        rwd          front      109.1  ...         141        mpfi   

     boreratio  stroke compressionratio horsepower  peakrpm citympg  \
200       3.78    3.15              9.5        114     5400      23   
201       3.78    3.15              8.7        160     5300      19   
202       3.58    2.87              8.8        134     5500      18   
203       3.01    3.40             23.0        106     4800      26   
204       3.78    3.15              9.5        114     5400      19   

     highwaympg    price  
200          28  16845.0  
201          25  19045.0  
202          23  21485.0  
203          27  22470.0  
204          25  22625.0  

[5 rows x 26 columns]

In [6]:
CarPrice.shape #the Dataset is having 205 rows and 26 columns

(205, 26)

In [7]:
CarPrice.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

*  The dataset contains 205 rows and 26 columns
*   Every person has information related of  CarPrices dataset related to 'car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'



In [8]:
CarPrice.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [9]:
CarPrice.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

No missing value is present in the dataset

*  No missing value is present in the dataset



In [10]:
CarPrice.duplicated().sum()

0

In [ ]:
#No duplicate value is present in the dataset

In [12]:
correlation_matrix = CarPrice[['car_ID', 'price']].corr()

In [13]:
print(correlation_matrix)

          car_ID     price
car_ID  1.000000 -0.109093
price  -0.109093  1.000000


In [ ]:
#There is a negligible relationship between CarID and price

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le=LabelEncoder()

In [21]:
for i in CarPrice.columns:
  if CarPrice[i].dtypes=='object':
    CarPrice[i]=le.fit_transform(CarPrice[i])





In [22]:
CarPrice.head()

car_ID  symboling  CarName  fueltype  aspiration  doornumber  carbody  \
0       1          3        2         1           0           1        0   
1       2          3        3         1           0           1        0   
2       3          1        1         1           0           1        2   
3       4          2        4         1           0           0        3   
4       5          2        5         1           0           0        3   

   drivewheel  enginelocation  wheelbase  ...  enginesize  fuelsystem  \
0           2               0       88.6  ...         130           5   
1           2               0       88.6  ...         130           5   
2           2               0       94.5  ...         152           5   
3           1               0       99.8  ...         109           5   
4           0               0       99.4  ...         136           5   

   boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
0       3.47    2.68               9.0         111     5000       21   
1       3.47    2.68               9.0         111     5000       21   
2       2.68    3.47               9.0         154     5000       19   
3       3.19    3.40              10.0         102     5500       24   
4       3.19    3.40               8.0         115     5500       18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [23]:
CarPrice.tail()

car_ID  symboling  CarName  fueltype  aspiration  doornumber  carbody  \
200     201         -1      139         1           0           0        3   
201     202         -1      138         1           1           0        3   
202     203         -1      140         1           0           0        3   
203     204         -1      142         0           1           0        3   
204     205         -1      143         1           1           0        3   

     drivewheel  enginelocation  wheelbase  ...  enginesize  fuelsystem  \
200           2               0      109.1  ...         141           5   
201           2               0      109.1  ...         141           5   
202           2               0      109.1  ...         173           5   
203           2               0      109.1  ...         145           3   
204           2               0      109.1  ...         141           5   

     boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
200       3.78    3.15               9.5         114     5400       23   
201       3.78    3.15               8.7         160     5300       19   
202       3.58    2.87               8.8         134     5500       18   
203       3.01    3.40              23.0         106     4800       26   
204       3.78    3.15               9.5         114     5400       19   

     highwaympg    price  
200          28  16845.0  
201          25  19045.0  
202          23  21485.0  
203          27  22470.0  
204          25  22625.0  

[5 rows x 26 columns]

In [24]:
CarPrice.corr()

car_ID  symboling   CarName  fueltype  aspiration  \
car_ID            1.000000  -0.151621  0.967077 -0.125568    0.067729   
symboling        -0.151621   1.000000 -0.107095  0.194311   -0.059866   
CarName           0.967077  -0.107095  1.000000 -0.069435    0.019914   
fueltype         -0.125568   0.194311 -0.069435  1.000000   -0.401397   
aspiration        0.067729  -0.059866  0.019914 -0.401397    1.000000   
doornumber       -0.190352   0.664073 -0.171745  0.191491   -0.031792   
carbody           0.098303  -0.596135  0.099691 -0.147853    0.063028   
drivewheel        0.051406  -0.041671 -0.016129 -0.132257    0.066465   
enginelocation    0.051483   0.212471  0.055968  0.040070   -0.057191   
wheelbase         0.129729  -0.531954  0.014550 -0.308346    0.257611   
carlength         0.170636  -0.357612  0.053016 -0.212679    0.234539   
carwidth          0.052387  -0.232919 -0.075349 -0.233880    0.300567   
carheight         0.255960  -0.541038  0.201900 -0.284631    0.087311   
curbweight        0.071962  -0.227691 -0.049407 -0.217275    0.324902   
enginetype       -0.075130   0.050372 -0.090381  0.082695   -0.102963   
cylindernumber   -0.040912   0.197762  0.047154  0.110617   -0.133119   
enginesize       -0.033930  -0.105790 -0.153982 -0.069594    0.108217   
fuelsystem        0.204898   0.091163  0.123845  0.041529    0.288086   
boreratio         0.260064  -0.130051  0.188598 -0.054451    0.212614   
stroke           -0.160824  -0.008735 -0.181775 -0.241829    0.222982   
compressionratio  0.150276  -0.178515  0.101730 -0.984356    0.295541   
horsepower       -0.015006   0.070873 -0.092131  0.163926    0.241685   
peakrpm          -0.203789   0.273606 -0.138309  0.476883   -0.183383   
citympg           0.015940  -0.035823  0.093437 -0.255963   -0.202362   
highwaympg        0.011255   0.034606  0.102895 -0.191392   -0.254416   
price            -0.109093  -0.079978 -0.231439 -0.105679    0.177926   

                  doornumber   carbody  drivewheel  enginelocation  wheelbase  \
car_ID             -0.190352  0.098303    0.051406        0.051483   0.129729   
symboling           0.664073 -0.596135   -0.041671        0.212471  -0.531954   
CarName            -0.171745  0.099691   -0.016129        0.055968   0.014550   
fueltype            0.191491 -0.147853   -0.132257        0.040070  -0.308346   
aspiration         -0.031792  0.063028    0.066465       -0.057191   0.257611   
doornumber          1.000000 -0.680358    0.098954        0.137757  -0.447357   
carbody            -0.680358  1.000000   -0.155745       -0.277009   0.401362   
drivewheel          0.098954 -0.155745    1.000000        0.147865   0.459745   
enginelocation      0.137757 -0.277009    0.147865        1.000000  -0.187790   
wheelbase          -0.447357  0.401362    0.459745       -0.187790   1.000000   
carlength          -0.398568  0.334433    0.485649       -0.050989   0.874587   
carwidth           -0.207168  0.131710    0.470751       -0.051698   0.795144   
carheight          -0.552208  0.568534   -0.019719       -0.106234   0.589435   
curbweight         -0.197379  0.128467    0.575111        0.050468   0.776386   
enginetype          0.062431 -0.037024   -0.116823        0.114127  -0.135577   
cylindernumber      0.154322 -0.048408    0.223238        0.135541  -0.184596   
enginesize         -0.020742 -0.073352    0.524307        0.196826   0.569329   
fuelsystem          0.015519 -0.065079    0.424686        0.105971   0.384601   
boreratio          -0.119258  0.010549    0.481827        0.185042   0.488750   
stroke              0.011082 -0.015325    0.071591       -0.138455   0.160959   
compressionratio   -0.177888  0.136243    0.127479       -0.019762   0.249786   
horsepower          0.126947 -0.153928    0.518686        0.317839   0.353294   
peakrpm             0.247668 -0.109643   -0.039417        0.198461  -0.360469   
citympg             0.012417  0.031697   -0.449581       -0.153487  -0.470414   
highwaympg          0.0

In [ ]:
#There is negative correlation between Symboling and Price i.e. -0.07.
#Positive correlation between DoorNumber and Symboling 0.66.

In [25]:
CarPrice.nunique() # count of unique values

car_ID              205
symboling             6
CarName             147
fueltype              2
aspiration            2
doornumber            2
carbody               5
drivewheel            3
enginelocation        2
wheelbase            53
carlength            75
carwidth             44
carheight            49
curbweight          171
enginetype            7
cylindernumber        7
enginesize           44
fuelsystem            8
boreratio            38
stroke               37
compressionratio     32
horsepower           59
peakrpm              23
citympg              29
highwaympg           30
price               189
dtype: int64

While you were understanding the data, what were the various statistical findings
and tests you performed to gain insights from the data?

In [26]:
CarPrice.describe()    #we can find out the mean,median,mode of data

car_ID   symboling     CarName    fueltype  aspiration  doornumber  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146   77.209756    0.902439    0.180488    0.439024   
std     59.322565    1.245307   41.014583    0.297446    0.385535    0.497483   
min      1.000000   -2.000000    0.000000    0.000000    0.000000    0.000000   
25%     52.000000    0.000000   44.000000    1.000000    0.000000    0.000000   
50%    103.000000    1.000000   80.000000    1.000000    0.000000    0.000000   
75%    154.000000    2.000000  115.000000    1.000000    0.000000    1.000000   
max    205.000000    3.000000  146.000000    1.000000    1.000000    1.000000   

          carbody  drivewheel  enginelocation   wheelbase  ...  enginesize  \
count  205.000000  205.000000      205.000000  205.000000  ...  205.000000   
mean     2.614634    1.326829        0.014634   98.756585  ...  126.907317   
std      0.859081    0.556171        0.120377    6.021776  ...   41.642693   
min      0.000000    0.000000        0.000000   86.600000  ...   61.000000   
25%      2.000000    1.000000        0.000000   94.500000  ...   97.000000   
50%      3.000000    1.000000        0.000000   97.000000  ...  120.000000   
75%      3.000000    2.000000        0.000000  102.400000  ...  141.000000   
max      4.000000    2.000000        1.000000  120.900000  ...  326.000000   

       fuelsystem   boreratio      stroke  compressionratio  horsepower  \
count  205.000000  205.000000  205.000000        205.000000  205.000000   
mean     3.253659    3.329756    3.255415         10.142537  104.117073   
std      2.013204    0.270844    0.313597          3.972040   39.544167   
min      0.000000    2.540000    2.070000          7.000000   48.000000   
25%      1.000000    3.150000    3.110000          8.600000   70.000000   
50%      5.000000    3.310000    3.290000          9.000000   95.000000   
75%      5.000000    3.580000    3.410000          9.400000  116.000000   
max      7.000000    3.940000    4.170000         23.000000  288.000000   

           peakrpm     citympg  highwaympg         price  
count   205.000000  205.000000  205.000000    205.000000  
mean   5125.121951   25.219512   30.751220  13276.710571  
std     476.985643    6.542142    6.886443   7988.852332  
min    4150.000000   13.000000   16.000000   5118.000000  
25%    4800.000000   19.000000   25.000000   7788.000000  
50%    5200.000000   24.000000   30.000000  10295.000000  
75%    5500.000000   30.000000   34.000000  16503.000000  
max    6600.000000   49.000000   54.000000  45400.000000  

[8 rows x 26 columns]

In [ ]:
#we can calculate the the mean,median,standard deviation ,minimum and maximum values
#For example  mean of carbody column is 2.61 ,minimum value is 0 ,and maximum value is 4 having standard deviation as 0.85

In [ ]:
#we can find out for the rest of the columns



* Null Hypotheises : It was observed that averagePrice generated by hatchback is 2.61
*  Alternate Hypothesis:The mean is not 2.61



In [ ]:
# We need to grab the data for Na_to_K and drug X

In [28]:
new_df=CarPrice.loc[(CarPrice['carbody']==2)]

In [29]:
new_df.shape

(70, 26)

In [30]:
new_df.head()

car_ID  symboling  CarName  fueltype  aspiration  doornumber  carbody  \
2        3          1        1         1           0           1        2   
9       10          0        8         1           1           1        2   
18      19          2       24         1           0           1        2   
19      20          1       25         1           0           1        2   
21      22          1       35         1           0           1        2   

    drivewheel  enginelocation  wheelbase  ...  enginesize  fuelsystem  \
2            2               0       94.5  ...         152           5   
9            0               0       99.5  ...         131           5   
18           1               0       88.4  ...          61           1   
19           1               0       94.5  ...          90           1   
21           1               0       93.7  ...          90           1   

    boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
2        2.68    3.47              9.00         154     5000       19   
9        3.13    3.40              7.00         160     5500       16   
18       2.91    3.03              9.50          48     5100       47   
19       3.03    3.11              9.60          70     5400       38   
21       2.97    3.23              9.41          68     5500       37   

    highwaympg      price  
2           26  16500.000  
9           22  17859.167  
18          53   5151.000  
19          43   6295.000  
21          41   5572.000  

[5 rows x 26 columns]

In [31]:
new_df.shape

(70, 26)

In [32]:
sample_df=new_df.sample(30,random_state=0)

In [33]:
proposed_mean=2.61

In [34]:
from scipy.stats import ttest_1samp

In [37]:
tstatistics_value,p_value=ttest_1samp(sample_df['price'],proposed_mean)

In [39]:
if p_value>0.05:
  print(" Reject Null Hypotheisis,there is  enough evidence to conclude that the average is  2.61")
else:
  print('Accept the Null Hypotheisis,there is  enough evidence to conclude that the average is  2.61')


Accept the Null Hypotheisis,there is  enough evidence to conclude that the average is  2.61


In [40]:
print(f'the Pvalue', {p_value})

the Pvalue {6.048752881689812e-13}


**Are the variance of wheelbase significantly different between hatchback and sedan    with gas fueltype**



*  Null Hypothesis:Variance of wheelbase  will be equal
*   Alternate hypothesis:Variance of wheelbase will not be equal




In [42]:
new_df_hatchback=CarPrice[(CarPrice['carbody']==2) & (CarPrice['fueltype']==1)]

In [43]:
new_df_hatchback.shape

(69, 26)

In [50]:
new_df_sedan=CarPrice[(CarPrice['carbody']==3) & (CarPrice['fueltype']==1)]

In [51]:
new_df_sedan.shape

(81, 26)

**Sampling**

In [53]:
sample_hatchback=new_df_hatchback.sample(30,random_state=0)
sample_sedan=new_df_sedan.sample(30,random_state=0)

In [55]:
a=sample_hatchback['wheelbase'].var()
b=sample_sedan['wheelbase'].var()

In [56]:
print(f'Variance of drugY ,{a}')
print(f'Variance of drugA ,{b}')

Variance of drugY ,14.033206896551729
Variance of drugA ,34.10717241379311


In [57]:
from scipy.stats import f

In [58]:
F=a/b

In [59]:
print(f"Ftest statistics",{F})

Ftest statistics {0.4114444529818787}


In [63]:
dof_hatchback=len(sample_hatchback)-1
dof_sedan=len(sample_sedan)-1

In [64]:
import scipy
p_value=scipy.stats.f.cdf(F,dof_hatchback,dof_sedan)

In [65]:
if p_value>0.05:
  print('Failed to reject Null hypothesis,using this we can conclude there is enough evidences to conclude that Wheelbase will be equal')
else:
  print('Reject the null Hypotheisis there is not enough evidence to conclude that wheelbase will not be equal')

Reject the null Hypotheisis there is not enough evidence to conclude that wheelbase will not be equal


After understanding the data, what was your approach to creating a
machine-learning model, for the feature selection and other important steps
before you could finalize your findings?

**Based on the data that we have got we can use LinearRegression model**

In [67]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [70]:
scaled_CarPrice=scaler.fit_transform(CarPrice)

In [74]:
from sklearn.feature_selection import SelectKBest,chi2
chi2_feature=SelectKBest(chi2,k=5)

In [66]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [76]:
x=CarPrice.iloc[:,::-1]
y=CarPrice.iloc[:,-1]
CarPrice.head()

car_ID  symboling  CarName  fueltype  aspiration  doornumber  carbody  \
0       1          3        2         1           0           1        0   
1       2          3        3         1           0           1        0   
2       3          1        1         1           0           1        2   
3       4          2        4         1           0           0        3   
4       5          2        5         1           0           0        3   

   drivewheel  enginelocation  wheelbase  ...  enginesize  fuelsystem  \
0           2               0       88.6  ...         130           5   
1           2               0       88.6  ...         130           5   
2           2               0       94.5  ...         152           5   
3           1               0       99.8  ...         109           5   
4           0               0       99.4  ...         136           5   

   boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
0       3.47    2.68               9.0         111     5000       21   
1       3.47    2.68               9.0         111     5000       21   
2       2.68    3.47               9.0         154     5000       19   
3       3.19    3.40              10.0         102     5500       24   
4       3.19    3.40               8.0         115     5500       18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [80]:
x=x.drop('symboling',axis=1)

In [89]:
x

price  highwaympg  citympg  peakrpm  horsepower  compressionratio  \
0    13495.0          27       21     5000         111               9.0   
1    16500.0          27       21     5000         111               9.0   
2    16500.0          26       19     5000         154               9.0   
3    13950.0          30       24     5500         102              10.0   
4    17450.0          22       18     5500         115               8.0   
..       ...         ...      ...      ...         ...               ...   
200  16845.0          28       23     5400         114               9.5   
201  19045.0          25       19     5300         160               8.7   
202  21485.0          23       18     5500         134               8.8   
203  22470.0          27       26     4800         106              23.0   
204  22625.0          25       19     5400         114               9.5   

     stroke  boreratio  fuelsystem  enginesize  ...  carlength  wheelbase  \
0      2.68       3.47           5         130  ...      168.8       88.6   
1      2.68       3.47           5         130  ...      168.8       88.6   
2      3.47       2.68           5         152  ...      171.2       94.5   
3      3.40       3.19           5         109  ...      176.6       99.8   
4      3.40       3.19           5         136  ...      176.6       99.4   
..      ...        ...         ...         ...  ...        ...        ...   
200    3.15       3.78           5         141  ...      188.8      109.1   
201    3.15       3.78           5         141  ...      188.8      109.1   
202    2.87       3.58           5         173  ...      188.8      109.1   
203    3.40       3.01           3         145  ...      188.8      109.1   
204    3.15       3.78           5         141  ...      188.8      109.1   

     enginelocation  drivewheel  carbody  doornumber  aspiration  fueltype  \
0                 0           2        0           1           0         1   
1                 0           2        0           1           0         1   
2                 0           2        2           1           0         1   
3                 0           1        3           0           0         1   
4                 0           0        3           0           0         1   
..              ...         ...      ...         ...         ...       ...   
200               0           2        3           0           0         1   
201               0           2        3           0           1         1   
202               0           2        3           0           0         1   
203               0           2        3           0           1         0   
204               0           2        3           0           1         1   

     CarName  car_ID  
0          2       1  
1          3       2  
2          1       3  
3          4       4  
4          5       5  
..       ...     ...  
200      139     201  
201      138     202  
202      140     203  
203      142     204  
204      143     205  

[205 rows x 25 columns]

In [77]:
chi2_feature=SelectKBest(chi2,k=5)

In [84]:
print(type(y))  # Should be a Pandas Series or a Numpy array
print(y.shape)  # Should be (n_samples,)
print(y.dtype)

<class 'pandas.core.series.Series'>
(205,)
float64


In [92]:
y = y.ravel()
y=y.astype(int)

In [93]:
x_Best_feature=chi2_feature.fit_transform(x,y)
print("Selected indices:",chi2_feature.get_support(indices=True))
selected_indices=chi2_feature.get_support(indices=True)
selected_indices
column_names=x.columns

Selected indices: [ 0  3 12 23 24]


In [94]:
selected_indices=chi2_feature.get_support(indices=True)
selected_indices
column_names=x.columns

In [95]:
selected_column_names=[column_names[i] for i  in selected_indices]
selected_column_names

['price', 'peakrpm', 'curbweight', 'CarName', 'car_ID']

In [97]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

            Features          VIF
0             car_ID   111.554210
1          symboling     4.123112
2            CarName   125.201594
3           fueltype   855.146658
4         aspiration     3.467627
5         doornumber     5.029344
6            carbody    28.884527
7         drivewheel    17.286037
8     enginelocation     1.760854
9          wheelbase  2925.630295
10         carlength  2390.007716
11          carwidth  6132.982735
12         carheight  1258.561556
13        curbweight   477.239139
14        enginetype    15.361359
15    cylindernumber    19.021318
16        enginesize   142.473262
17        fuelsystem     9.364260
18         boreratio   347.850943
19            stroke   165.133955
20  compressionratio   619.161605
21        horsepower   113.145177
22           peakrpm   317.967611
23           citympg   525.601103
24        highwaympg   598.384015


In [99]:
CarPrice=CarPrice.drop('car_ID',axis=1)

In [100]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

            Features          VIF
0          symboling     4.105172
1            CarName     6.803250
2           fueltype   840.792903
3         aspiration     3.462795
4         doornumber     5.019874
5            carbody    28.722719
6         drivewheel    17.167178
7     enginelocation     1.759992
8          wheelbase  2920.349224
9          carlength  2370.093846
10          carwidth  6074.628596
11         carheight  1258.128226
12        curbweight   476.727493
13        enginetype    14.731469
14    cylindernumber    16.423326
15        enginesize   142.349602
16        fuelsystem     9.194469
17         boreratio   344.192339
18            stroke   165.114544
19  compressionratio   603.786984
20        horsepower   113.048089
21           peakrpm   314.740150
22           citympg   523.798541
23        highwaympg   588.343868


In [101]:
CarPrice=CarPrice.drop('compressionratio',axis=1)

In [102]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features          VIF
0        symboling     4.104251
1          CarName     6.479152
2         fueltype    27.296089
3       aspiration     3.058997
4       doornumber     5.019122
5          carbody    28.591530
6       drivewheel    17.010282
7   enginelocation     1.759775
8        wheelbase  2766.053275
9        carlength  2328.586785
10        carwidth  4370.163359
11       carheight  1180.380945
12      curbweight   462.099063
13      enginetype    14.635158
14  cylindernumber    13.219589
15      enginesize   139.202910
16      fuelsystem     9.139293
17       boreratio   344.140083
18          stroke   154.758368
19      horsepower   113.032219
20         peakrpm   284.744731
21         citympg   503.875945
22      highwaympg   588.281401


In [103]:
CarPrice=CarPrice.drop('carheight',axis=1)

In [104]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features          VIF
0        symboling     4.103580
1          CarName     6.406637
2         fueltype    26.947605
3       aspiration     3.041980
4       doornumber     4.981259
5          carbody    27.732021
6       drivewheel    16.070303
7   enginelocation     1.604934
8        wheelbase  2509.836659
9        carlength  2250.201294
10        carwidth  4348.824912
11      curbweight   456.204412
12      enginetype    14.617313
13  cylindernumber    13.080054
14      enginesize   134.044636
15      fuelsystem     9.087340
16       boreratio   341.780449
17          stroke   154.749139
18      horsepower   112.908466
19         peakrpm   284.530692
20         citympg   500.620917
21      highwaympg   587.782477


In [105]:
CarPrice=CarPrice.drop('carlength',axis=1)

In [106]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features          VIF
0        symboling     4.058593
1          CarName     6.317806
2         fueltype    26.919315
3       aspiration     2.997005
4       doornumber     4.898077
5          carbody    26.106334
6       drivewheel    16.060250
7   enginelocation     1.593622
8        wheelbase  2163.075202
9         carwidth  3720.694478
10      curbweight   437.624341
11      enginetype    14.042051
12  cylindernumber    13.025440
13      enginesize   133.614931
14      fuelsystem     8.879367
15       boreratio   336.881912
16          stroke   154.714534
17      horsepower   110.674513
18         peakrpm   284.184041
19         citympg   481.098504
20      highwaympg   583.105531


In [111]:
CarPrice=CarPrice.drop('carwidth',axis=1)

In [112]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features         VIF
0        symboling    3.498657
1          CarName    6.312459
2         fueltype   24.828625
3       aspiration    2.945618
4       doornumber    4.897719
5          carbody   24.656400
6       drivewheel   14.715446
7   enginelocation    1.560482
8       curbweight  244.159816
9       enginetype   11.707398
10  cylindernumber   12.747195
11      enginesize  129.296197
12      fuelsystem    8.765157
13       boreratio  256.339574
14          stroke  143.609295
15      horsepower   89.962363
16         peakrpm  213.698182
17         citympg  476.244299
18      highwaympg  556.486634


In [113]:
CarPrice=CarPrice.drop('highwaympg',axis=1)

In [114]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features         VIF
0        symboling    3.338048
1          CarName    6.312099
2         fueltype   24.824376
3       aspiration    2.672562
4       doornumber    4.765729
5          carbody   24.651614
6       drivewheel   14.709313
7   enginelocation    1.553522
8       curbweight  241.234287
9       enginetype   11.667808
10  cylindernumber   12.715785
11      enginesize  120.951590
12      fuelsystem    8.737507
13       boreratio  249.205824
14          stroke  132.572253
15      horsepower   80.960354
16         peakrpm  212.200400
17         citympg   54.185035


In [115]:
CarPrice=CarPrice.drop('curbweight',axis=1)

In [116]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features         VIF
0        symboling    3.335166
1          CarName    6.301799
2         fueltype   22.288248
3       aspiration    2.530865
4       doornumber    4.723356
5          carbody   23.545390
6       drivewheel   14.363674
7   enginelocation    1.444578
8       enginetype   11.528482
9   cylindernumber   12.609764
10      enginesize   79.689693
11      fuelsystem    8.631360
12       boreratio  190.572369
13          stroke  132.231428
14      horsepower   80.241622
15         peakrpm  194.916429
16         citympg   46.049777


In [117]:
CarPrice=CarPrice.drop('boreratio',axis=1)

In [118]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features         VIF
0        symboling    3.307831
1          CarName    5.450978
2         fueltype   20.988440
3       aspiration    2.365389
4       doornumber    4.696788
5          carbody   22.931728
6       drivewheel   12.988224
7   enginelocation    1.443361
8       enginetype   10.904248
9   cylindernumber   12.585866
10      enginesize   70.998054
11      fuelsystem    8.592558
12          stroke  129.057573
13      horsepower   80.098155
14         peakrpm  183.968760
15         citympg   43.446059


In [119]:
CarPrice=CarPrice.drop('peakrpm',axis=1)

In [120]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features        VIF
0        symboling   3.238578
1          CarName   5.413169
2         fueltype  16.874466
3       aspiration   2.320613
4       doornumber   4.681001
5          carbody  20.508798
6       drivewheel  12.277839
7   enginelocation   1.406442
8       enginetype  10.466783
9   cylindernumber  12.543999
10      enginesize  56.835881
11      fuelsystem   8.570704
12          stroke  95.097212
13      horsepower  64.034861
14         citympg  35.243096


In [121]:
CarPrice=CarPrice.drop('stroke',axis=1)

In [122]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features        VIF
0        symboling   3.156968
1          CarName   5.373915
2         fueltype  15.477599
3       aspiration   2.070429
4       doornumber   4.680624
5          carbody  19.761784
6       drivewheel  12.187993
7   enginelocation   1.386471
8       enginetype  10.466125
9   cylindernumber  12.073106
10      enginesize  47.976722
11      fuelsystem   8.344635
12      horsepower  63.832398
13         citympg  19.766538


In [123]:
CarPrice=CarPrice.drop('horsepower',axis=1)

In [124]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features        VIF
0        symboling   3.156695
1          CarName   5.371160
2         fueltype  11.376630
3       aspiration   1.628535
4       doornumber   4.544504
5          carbody  19.632174
6       drivewheel  12.139000
7   enginelocation   1.213963
8       enginetype  10.231469
9   cylindernumber  11.051278
10      enginesize  17.932548
11      fuelsystem   7.877886
12         citympg  15.927513


In [125]:
CarPrice=CarPrice.drop('enginetype',axis=1)

In [126]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list=[]
for col in CarPrice.columns:
  if ((CarPrice[col].dtype !='object' )& (col!='price')):
    col_list.append(col)

x=CarPrice[col_list]
Vif_data=pd.DataFrame()
Vif_data['Features']=x.columns
Vif_data['VIF']=[variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
print(Vif_data)

          Features        VIF
0        symboling   3.156573
1          CarName   5.368801
2         fueltype  11.163664
3       aspiration   1.626801
4       doornumber   4.529427
5          carbody  19.514804
6       drivewheel  11.669795
7   enginelocation   1.207470
8   cylindernumber   9.872560
9       enginesize  16.206516
10      fuelsystem   7.858136
11         citympg  15.452968


In [127]:
X=CarPrice.drop('price',axis=1)
y=CarPrice['price']

In [128]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [129]:
linreg=LinearRegression()

In [130]:
linreg.fit(X_train,y_train)


LinearRegression()

In [131]:
y_pred=linreg.predict(X_test)

When you created the model, how did you evaluate the model, and what are
some of the suggestions for improving the performance of the model?

In [136]:
from sklearn.metrics import r2_score

In [138]:
r2_score(y_test,y_pred)

0.7951312406635641

In [ ]:
#r2_score is coming 0.79 means our model is a good model